---
- name: Création de tags automatiques sur Dynatrace
  hosts: localhost
  gather_facts: no
  vars:
    dynatrace_environment_id: "votre-environment-id"
    dynatrace_api_token: "votre-api-token"
    vm_list:
      - { name: "VM1", tag: "AP-VM1" }
      - { name: "VM2", tag: "AP-VM2" }
      - { name: "VM3", tag: "AP-VM3" }
      - { name: "VM4", tag: "AP-VM4" }

  tasks:
    - name: Créer des tags automatiques pour chaque VM
      uri:
        url: "https://{{ dynatrace_environment_id }}.live.dynatrace.com/api/v2/settings/objects"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Api-Token {{ dynatrace_api_token }}"
        body: |
          {
            "schemaId": "builtin:tags.auto-tagging",
            "scope": "environment",
            "value": {
              "name": "{{ item.tag }}",
              "description": "Tag automatique pour {{ item.name }}",
              "rules": [
                {
                  "enabled": true,
                  "entitySelector": "type(\"PROCESS_GROUP_INSTANCE\"),fromRelationship.isProcessOf(type(\"HOST\"),entityName(\"{{ item.name }}\"))"
                },
                {
                  "enabled": true,
                  "entitySelector": "type(\"SERVICE\"),fromRelationships.runsOnHost(type(\"HOST\"),entityName(\"{{ item.name }}\"))"
                },
                {
                  "enabled": true,
                  "entitySelector": "type(\"HOST\"),entityName.contains(\"{{ item.name }}\")"
                },
                {
                  "enabled": true,
                  "entitySelector": "type(\"WEB_APPLICATION\"),entityName.contains(\"{{ item.name | lower }}\")"
                }
              ]
            }
          }
        body_format: json
        status_code: 201
      loop: "{{ vm_list }}"
      loop_control:
        label: "{{ item.name }}"
